#!/usr/bin/env bash
# Aegis Core — Interactive setup script
# Generates .env with strong secrets, creates data directory, and prints next steps.
set -euo pipefail

BOLD='\033[1m'
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
RESET='\033[0m'

say()  { echo -e "${CYAN}${BOLD}[aegis]${RESET} $*"; }
ok()   { echo -e "${GREEN}✓${RESET} $*"; }
warn() { echo -e "${YELLOW}⚠${RESET} $*"; }
die()  { echo -e "${RED}✗${RESET} $*"; exit 1; }

echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${BOLD}  Aegis Core — Self-Hosted Setup${RESET}"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""
say "This script will:"
echo "  • Generate cryptographically secure secrets"
echo "  • Create a .env file with your configuration"
echo "  • Create the ./data directory for the database and packets"
echo "  • Print Docker Compose next steps"
echo ""

# ── Check for existing .env ───────────────────────────────────────────────────

if [[ -f ".env" ]]; then
  warn ".env already exists."
  read -rp "  Overwrite it? [y/N] " overwrite
  if [[ ! "${overwrite}" =~ ^[Yy]$ ]]; then
    die "Aborted. Existing .env preserved."
  fi
fi

# ── Secret generation ─────────────────────────────────────────────────────────

gen_secret() {
  local nbytes="${1:-32}"
  if command -v openssl &>/dev/null; then
    openssl rand -hex "${nbytes}"
  elif command -v node &>/dev/null; then
    node -e "process.stdout.write(require('crypto').randomBytes(${nbytes}).toString('hex'))"
  else
    head -c "${nbytes}" /dev/urandom | od -A n -t x1 | tr -d ' \n'
  fi
}

say "Generating secrets…"
SECRET_KEY="$(gen_secret 64)"
FIELD_KEY="$(gen_secret 32)"
ok "AEGIS_SECRET_KEY generated (128 hex chars)"
ok "AEGIS_FIELD_ENCRYPTION_KEY generated (64 hex chars)"

# ── App URL and port ──────────────────────────────────────────────────────────

echo ""
say "App configuration"
read -rp "  App URL [http://localhost:8000]: " APP_URL
APP_URL="${APP_URL:-http://localhost:8000}"
read -rp "  Port [8000]: " APP_PORT
APP_PORT="${APP_PORT:-8000}"

# ── Optional providers ────────────────────────────────────────────────────────

echo ""
say "Optional providers (can be configured later in Settings)"

SMTP_SECTION=""
read -rp "  Configure SMTP now? [y/N] " do_smtp
if [[ "${do_smtp}" =~ ^[Yy]$ ]]; then
  read -rp "    SMTP host: " SMTP_HOST
  read -rp "    SMTP port [587]: " SMTP_PORT
  SMTP_PORT="${SMTP_PORT:-587}"
  read -rp "    SMTP user (username/email): " SMTP_USER
  read -rsp "    SMTP password: " SMTP_PASS
  echo ""
  read -rp "    From email: " SMTP_FROM
  SMTP_SECTION="AEGIS_SMTP_HOST=${SMTP_HOST}
AEGIS_SMTP_PORT=${SMTP_PORT}
AEGIS_SMTP_USER=${SMTP_USER}
AEGIS_SMTP_PASSWORD=${SMTP_PASS}
AEGIS_SMTP_FROM=${SMTP_FROM}"
  ok "SMTP configured"
else
  SMTP_SECTION="# AEGIS_SMTP_HOST=
# AEGIS_SMTP_PORT=587
# AEGIS_SMTP_USER=
# AEGIS_SMTP_PASSWORD=
# AEGIS_SMTP_FROM="
  warn "SMTP skipped — configure in Settings → Notifications after first login"
fi

TG_SECTION=""
read -rp "  Configure Telegram now? [y/N] " do_telegram
if [[ "${do_telegram}" =~ ^[Yy]$ ]]; then
  read -rsp "    Telegram bot token: " TG_TOKEN
  echo ""
  read -rp "    Telegram chat ID: " TG_CHAT
  TG_SECTION="AEGIS_TELEGRAM_BOT_TOKEN=${TG_TOKEN}
AEGIS_TELEGRAM_CHAT_ID=${TG_CHAT}"
  ok "Telegram configured"
else
  TG_SECTION="# AEGIS_TELEGRAM_BOT_TOKEN=
# AEGIS_TELEGRAM_CHAT_ID="
  warn "Telegram skipped — configure in Settings → Notifications after first login"
fi

S3_SECTION=""
read -rp "  Configure S3-compatible storage (Dead Drop) now? [y/N] " do_s3
if [[ "${do_s3}" =~ ^[Yy]$ ]]; then
  read -rp "    S3 endpoint (blank for AWS S3): " S3_ENDPOINT
  read -rp "    S3 region [us-east-1]: " S3_REGION
  S3_REGION="${S3_REGION:-us-east-1}"
  read -rp "    S3 bucket name: " S3_BUCKET
  read -rp "    S3 access key ID: " S3_KEY_ID
  read -rsp "    S3 secret access key: " S3_SECRET
  echo ""
  read -rp "    S3 key prefix [aegis]: " S3_PREFIX
  S3_PREFIX="${S3_PREFIX:-aegis}"
  S3_SECTION="AEGIS_S3_ENDPOINT=${S3_ENDPOINT}
AEGIS_S3_REGION=${S3_REGION}
AEGIS_S3_BUCKET=${S3_BUCKET}
AEGIS_S3_ACCESS_KEY_ID=${S3_KEY_ID}
AEGIS_S3_SECRET_ACCESS_KEY=${S3_SECRET}
AEGIS_S3_PREFIX=${S3_PREFIX}"
  ok "S3 storage configured"
else
  S3_SECTION="# AEGIS_S3_ENDPOINT=
# AEGIS_S3_REGION=us-east-1
# AEGIS_S3_BUCKET=
# AEGIS_S3_ACCESS_KEY_ID=
# AEGIS_S3_SECRET_ACCESS_KEY=
# AEGIS_S3_PREFIX=aegis"
  warn "S3 skipped — configure in Settings → Storage after first login"
fi

# ── Write .env ────────────────────────────────────────────────────────────────

say "Writing .env…"
cat > .env <<EOF
# Aegis Core configuration — generated by setup.sh
# Keep this file private. Back it up securely.
NODE_ENV=production

AEGIS_PORT=${APP_PORT}
AEGIS_HOST=0.0.0.0
AEGIS_APP_URL=${APP_URL}
AEGIS_DB_PATH=/data/aegis.db
AEGIS_DATA_DIR=/data

# Secrets — never share these
AEGIS_SECRET_KEY=${SECRET_KEY}
AEGIS_FIELD_ENCRYPTION_KEY=${FIELD_KEY}

# Notifications
${SMTP_SECTION}

${TG_SECTION}

# Storage (Dead Drop)
${S3_SECTION}
EOF

ok ".env written"

# ── Create data directory ─────────────────────────────────────────────────────

mkdir -p ./data/packets
ok "./data directory created"

# ── Print next steps ──────────────────────────────────────────────────────────

echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${GREEN}${BOLD}Setup complete!${RESET}"
echo ""
echo -e "  ${BOLD}Start with Docker Compose:${RESET}"
echo "    docker compose up -d"
echo ""
echo -e "  ${BOLD}Then open your browser at:${RESET}"
echo "    ${APP_URL}"
echo ""
echo -e "  ${BOLD}The first visit will guide you through owner account creation.${RESET}"
echo ""
echo -e "${YELLOW}${BOLD}Important security reminders:${RESET}"
echo -e "  ${YELLOW}•${RESET} Your .env contains secrets. Keep it private and back it up securely."
echo -e "  ${YELLOW}•${RESET} Your database and data directory contain encrypted but sensitive application state."
echo -e "  ${YELLOW}•${RESET} Vault Mode alone does not guarantee automated release if this host goes offline."
echo -e "  ${YELLOW}•${RESET} Back up your .env and data/ together — neither is useful without the other."
echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
