import { randomUUID } from 'crypto';
import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { eq, inArray } from 'drizzle-orm';
import type { AegisDb } from '../db/index.js';
import { owner, switches, estateItems, contacts } from '../db/schema.js';
import { decryptField } from './field-encrypt.js';
import { encryptField } from './field-encrypt.js';
import { generatePacketKey, encryptPacketJson, serializeEncryptedPacket } from './packet-crypto.js';
import {
  createPacketRecord,
  getNextPacketVersion,
  storePacketKey,
  type PacketRecord,
} from '../repositories/packet-repository.js';
import { writeAuditEvent } from './audit.js';

const SCHEMA_VERSION = '1.0';
const DISCLAIMERS = [
  'This packet was generated by Aegis Core and is intended solely for the named recipient.',
  'Verify the sender identity before acting on the contents of this packet.',
];

interface LegacyPacketPayload {
  schemaVersion: string;
  generatedAt: string;
  sourceApp: 'aegis_core';
  owner: {
    displayName: string;
    email: string | null;
    timezone: string;
  };
  switch: {
    id: number;
    name: string;
    mode: string;
    deploymentMode: string;
  };
  estateItems: Array<{
    category: string;
    title: string;
    institutionName: string | null;
    accountType: string | null;
    referenceHint: string | null;
    assetDescription: string | null;
    locationNotes: string | null;
    executorNotes: string | null;
  }>;
  contacts: Array<{
    priorityOrder: number;
    fullName: string;
    relationship: string | null;
    email: string | null;
    phone: string | null;
    telegramHandle: string | null;
  }>;
  disclaimers: string[];
}

export class PacketBuildError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'PacketBuildError';
  }
}

export async function buildPacket(
  db: AegisDb,
  fieldEncryptionKey: string,
  dataDir: string,
  switchId: number,
): Promise<PacketRecord> {
  const ownerRows = await db.select().from(owner).limit(1);
  if (ownerRows.length === 0) throw new PacketBuildError('Owner not found');
  const ownerRow = ownerRows[0];

  const switchRows = await db.select().from(switches).where(eq(switches.id, switchId));
  if (switchRows.length === 0) throw new PacketBuildError(`Switch ${switchId} not found`);
  const sw = switchRows[0];

  const selectedItemIds: number[] = JSON.parse(sw.selectedEstateItemIds ?? '[]');
  const selectedContactIds: number[] = JSON.parse(sw.selectedContactIds ?? '[]');

  if (selectedItemIds.length === 0) {
    throw new PacketBuildError('Switch has no selected estate items');
  }
  if (selectedContactIds.length === 0) {
    throw new PacketBuildError('Switch has no selected contacts');
  }

  const itemRows = await db
    .select()
    .from(estateItems)
    .where(inArray(estateItems.id, selectedItemIds));
  if (itemRows.length !== selectedItemIds.length) {
    throw new PacketBuildError('One or more selected estate items not found');
  }

  const contactRows = await db
    .select()
    .from(contacts)
    .where(inArray(contacts.id, selectedContactIds));
  if (contactRows.length !== selectedContactIds.length) {
    throw new PacketBuildError('One or more selected contacts not found');
  }

  const payload: LegacyPacketPayload = {
    schemaVersion: SCHEMA_VERSION,
    generatedAt: new Date().toISOString(),
    sourceApp: 'aegis_core',
    owner: {
      displayName: ownerRow.displayName,
      email: ownerRow.email,
      timezone: ownerRow.timezone,
    },
    switch: {
      id: sw.id,
      name: sw.name,
      mode: sw.mode,
      deploymentMode: sw.deploymentMode,
    },
    estateItems: itemRows.map((item) => ({
      category: item.category,
      title: item.title,
      institutionName: decryptField(item.institutionNameEncrypted, fieldEncryptionKey),
      accountType: decryptField(item.accountTypeEncrypted, fieldEncryptionKey),
      referenceHint: decryptField(item.referenceHintEncrypted, fieldEncryptionKey),
      assetDescription: decryptField(item.assetDescriptionEncrypted, fieldEncryptionKey),
      locationNotes: decryptField(item.locationNotesEncrypted, fieldEncryptionKey),
      executorNotes: decryptField(item.executorNotesEncrypted, fieldEncryptionKey),
    })),
    contacts: contactRows.map((c) => ({
      priorityOrder: c.priorityOrder,
      fullName: decryptField(c.fullNameEncrypted, fieldEncryptionKey)!,
      relationship: decryptField(c.relationshipEncrypted, fieldEncryptionKey),
      email: decryptField(c.emailEncrypted, fieldEncryptionKey),
      phone: decryptField(c.phoneEncrypted, fieldEncryptionKey),
      telegramHandle: decryptField(c.telegramHandleEncrypted, fieldEncryptionKey),
    })),
    disclaimers: DISCLAIMERS,
  };

  const packetKey = generatePacketKey();
  const keyId = randomUUID();
  const encrypted = encryptPacketJson(payload, packetKey, keyId);

  const packetsDir = join(dataDir, 'packets');
  mkdirSync(packetsDir, { recursive: true });
  const ciphertextPath = join(packetsDir, `${keyId}.bin`);
  writeFileSync(ciphertextPath, serializeEncryptedPacket(encrypted));

  const encryptedKeyMaterial = encryptField(packetKey.toString('base64'), fieldEncryptionKey)!;

  const version = await getNextPacketVersion(db, switchId);
  await storePacketKey(db, keyId, encryptedKeyMaterial);

  const record = await createPacketRecord(db, {
    switchId,
    version,
    schemaVersion: SCHEMA_VERSION,
    encryptionAlgorithm: encrypted.algorithm,
    keyId,
    contentHash: encrypted.contentHash,
    encryptedObjectHash: encrypted.encryptedObjectHash,
    localCiphertextPath: ciphertextPath,
  });

  await writeAuditEvent(db, {
    switchId,
    eventType: 'packet_generated',
    actorType: 'owner',
    metadata: { packetId: record.id, version, keyId },
  });

  return record;
}
